# Generated by Django 4.0 on 2021-12-28 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedLike',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('interest', models.ManyToManyField(blank=True, to='user.Interested')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='interestedlike',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
