# Generated by Django 4.0 on 2021-12-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_interestedlike_remove_profile_interest_delete_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedlike',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', unique=True),
        ),
    ]
