# Generated by Django 4.0 on 2022-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_interest_remove_interestedlike_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='created',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_category',
            field=models.ManyToManyField(blank=True, to='user.Interest'),
        ),
    ]
