# Generated by Django 4.0 on 2022-02-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_interest_created_remove_interest_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest_category',
            field=models.ManyToManyField(blank=True, related_name='interest', to='user.Interest'),
        ),
    ]
