# Generated by Django 4.0.3 on 2022-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_interest_owner_alter_profile_interest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/user-default.png', null=True, upload_to='profile/'),
        ),
    ]
