# Generated by Django 4.0 on 2021-12-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_topnews_news_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Top',
        ),
    ]
