# Generated by Django 4.0 on 2022-02-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_tag_news_vote_ratio_news_vote_total_review_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
