# Generated by Django 4.0.3 on 2022-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_vote_ratio_remove_news_vote_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='verified_news',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
